language: generic

jobs:
  include:
    - stage: Hello
      script: echo "Hello, World!"
    - stage: Hello-Again
      script: echo "Hello there!"
    - stage: Hey-Now  
      script: echo "Hey hey..!"